files:
  - source: /common/src/commonMain/i18n/tk/zwander/samloaderkotlin/strings_en.properties
    translation: /common/src/commonMain/i18n/tk/zwander/samloaderkotlin/strings_%two_letters_code%.properties
