# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build for macOS

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Get Latest Release
      id: release
      uses: rez0n/actions-github-release@main
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        type: "latest"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageDmg
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ${{ github.workspace }}/desktop/build/compose/logs/
    - name: Check Output Exists
      run: ls -laR ${{ github.workspace }}/desktop/build/compose/binaries/main/app/
    - name: Create Release ZIP
      uses: papeloto/action-zip@v1
      with:
        dest: 'Samsung_Firmware_Downloader_macOS.zip'
        files: desktop/build/compose/binaries/main/dmg/
    - name: Upload DMG
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Samsung Firmware Downloader
        path: ${{ github.workspace }}/desktop/build/compose/binaries/main/dmg/Samsung Firmware Downloader-*.dmg
    - name: Upload Release ZIP
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'Samsung_Firmware_Downloader_macOS.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        replacesArtifacts: false
        omitBodyDuringUpdate: true
        tag: ${{ steps.release.outputs.release }}
