# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build for macOS

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Get Latest Release
      id: release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        view_top: 1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageDmg
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ${{ github.workspace }}/desktop/build/compose/logs/
    - name: Check Output Exists
      run: ls -laR ${{ github.workspace }}/desktop/build/compose/binaries/main/dmg/
    - name: Import Certs
      uses: figleafteam/import-codesign-certs@v2
      id: importcerts
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
    - name: Sign Executable
      continue-on-error: true
      env:
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        WORKSPACE: ${{ github.workspace }}
        KEYCHAIN_NAME: ${{ steps.importcerts.outputs.keychain_name }}
        KEYCHAIN_PASS: ${{ steps.importcerts.output.keychain_password }}
      run: >
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12 ;
        security default-keychain -s $KEYCHAIN_NAME ;
        security unlock-keychain -p $KEYCHAIN_PASS $KEYCHAIN_NAME ;
        security import certificate.p12 -k $KEYCHAIN_NAME -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign ;
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD $KEYCHAIN_NAME ;
        security find-identity ;
        /usr/bin/codesign -fs "Zachary Wander Codesign 2" "$(ls $WORKSPACE//desktop/build/compose/binaries/main/dmg/Bifrost-*.dmg)"
    - name: Create Release ZIP
      uses: papeloto/action-zip@v1
      with:
        dest: 'Bifrost_macOS.zip'
        files: desktop/build/compose/binaries/main/dmg/
    - name: Upload DMG
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Bifrost
        path: ${{ github.workspace }}/desktop/build/compose/binaries/main/dmg/Bifrost-*.dmg
    - name: Upload Release ZIP
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'Bifrost_macOS.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        replacesArtifacts: false
        omitBodyDuringUpdate: true
        tag: ${{ steps.release.outputs.tag_name }}
